import { ProductsTypes } from "../../types";

export const Products = <ProductsTypes[]>[
  {
    id: 1,
    name: "Product 1",
    price: 7,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
  {
    id: 2,
    name: "Product 2",
    price: 27,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
  {
    id: 3,
    name: "Product 3",
    price: 60,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
  {
    id: 4,
    name: "Product 4",
    price: 40.9,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
  {
    id: 5,
    name: "Product 5",
    price: 32.5,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
  {
    id: 6,
    name: "Product 6",
    price: 30,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
  {
    id: 7,
    name: "Product 7",
    price: 75,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
  {
    id: 8,
    name: "Product 8",
    price: 50,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
  {
    id: 9,
    name: "Product 9",
    price: 20,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
  {
    id: 10,
    name: "Product 10",
    price: 12.9,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
  {
    id: 11,
    name: "Product 11",
    price: 40,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
  {
    id: 12,
    name: "Product 12",
    price: 36.5,
    image: "/images/product.jpg",
    compatibility: "Product compatible with all motorcycles",
  },
];
